### ISSUE TITLE
Problem with proxy

### ISSUE THREAD

**Issue by amusarra** [bridgecrewio/prisma-cloud-jetbrains-ide#138]
**Environment**: macOS 24.0.0 Darwin Kernel Version 24.0.0
**Python**: 3.12
**IDE**:  IntelliJ IDEA 2024.2.3 (Ultimate Edition)
**IDE Config**:

```text
IntelliJ IDEA 2024.2.3 (Ultimate Edition)
Build #IU-242.23339.11, built on September 25, 2024
Licensed to Liferay Portal Security Audit / Antonio Musarra
Subscription is active until November 22, 2024.
For non-commercial open source development only.
Runtime version: 21.0.4+13-b509.17 aarch64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.lwawt.macosx.LWCToolkit
macOS 15.0.1
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 2048M
Cores: 10
Registry:
  debugger.new.tool.window.layout=true
  ide.experimental.ui=true
  i18n.locale=
Non-Bundled Plugins:
  com.jetbrains.plugins.ini4idea (242.23339.18)
  com.github.bridgecrewio.prismacloud (1.0.22)
  com.mnr.java.intellij.idea.plugin.base64helper (2.0.3)
  com.jetbrains.darkPurpleTheme (1.3)
  com.jetbrains.space (242.23339.11)
  com.jetbrains.edu (2024.9-2024.2-1051)
  google-java-format (1.24.0.0)
  com.wrq.rearranger (6.0.18)
  com.intellij.properties.bundle.editor (242.22855.32)
  CheckStyle-IDEA (5.95.0)
  com.github.camork.fileExpander (2.5)
  com.intellij.mermaid (0.0.22+IJ.232)
  com.intellij.ml.llm (242.23339.40)
  org.asciidoctor.intellij.asciidoc (0.43.1)
  org.exbin.deltahex.intellij (0.2.10.1)
  io.snyk.snyk-intellij-plugin (2.9.1)
  com.github.copilot (1.5.25.10)
  org.sonarlint.idea (10.11.1.79663)
  zielu.gittoolbox (600.0.1+242)
Kotlin: 242.23339.11-IJ
```
Config 1 - Configuration of the IDE

When using the IntellijIDEA plugin, and it is configured to use a proxy, the plugin fails to connect to the endpoint. It seems that the plugin does not use the proxy set in the IDE or the system-wide proxy.

```
2024-10-08 12:14:40,284 [MainThread  ] [WARNI]  An unexpected error occurred getting the run configuration from https://<FQDN>/bridgecrew/api/v2/checkov/runConfiguration after multiple retries. Please verify your API key and Prisma API URL, and retry. If the problem persists, please enable debug logs and contact support. The error is: HTTPSConnectionPool(host='api.eu.prismacloud.io', port=443): Max retries exceeded with url: /login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x148affc80>, 'Connection to api.eu.prismacloud.io timed out. (connect timeout=3.1)'))
Traceback (most recent call last):
  File "/Users/amusarra/Library/Python/3.12/lib/python/site-packages/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amusarra/Library/Python/3.12/lib/python/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/Users/amusarra/Library/Python/3.12/lib/python/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: timed out
```
Log 1 - Connection timeout when setting the proxy

**Comment by ChananM** [comment]
You are correct, we do not pass IntelliJ proxy settings to Checkov, and this is indeed an issue. 
Can you please share how your proxy configuration looks under Appearance & Behavior | System Settings | HTTP Proxy?
If you can't share the data any mock values will suffice, I just want to make sure I reproduce the same issue.
By the way, if it can provide a temporary workaround, proxy configuration works in the VS Code extension

**Comment by amusarra** [comment]
Hi @ChananM 
I am using "Manual Proxy configuration" of HTTP type under Appearance & Behavior. I'm not using a publicly accessible proxy, so it wouldn't help you to have my proxy settings.

For Java projects I don't use VSCode and I don't want to use it.

I await your response.
Many thanks.

**Comment by ChananM** [comment]
@amusarra I won't be able (and won't need) to access your proxy, but I will be able to see what is your use case. That's why I said mock values are also fine. 
For example, are you using proxy authentication or not?
Either way, another workaround that might work until we'll fix this issue is to define your proxy as a global environment variable in your operating system (`HTTPS_PROXY` / `https_proxy` / `HTTP_PROXY` / `http_proxy`). I didn't try it myself but I think it should work.

**Comment by amusarra** [comment]
Proxy require authentication, and setting the username and password on the IDEA Proxy Configuration.

With the global proxy via environment, same problem.

**Comment by amusarra** [comment]
> @amusarra I won't be able (and won't need) to access your proxy, but I will be able to see what is your use case. That's why I said mock values are also fine. For example, are you using proxy authentication or not? Either way, another workaround that might work until we'll fix this issue is to define your proxy as a global environment variable in your operating system (`HTTPS_PROXY` / `https_proxy` / `HTTP_PROXY` / `http_proxy`). I didn't try it myself but I think it should work.

<img width="850" alt="image" src="https://github.com/user-attachments/assets/32414a4b-59e6-4c3a-8f32-31641c020190">

**Comment by amusarra** [comment]
Hi @ChananM 
I confirm, also with Visual Studio Code the same problem when I use the proxy (http).

**Comment by amusarra** [comment]
Hi @ChananM 
I confirm, also with Visual Studio Code the same problem when I use the proxy (http).

1. export proxy setting via command `export HTTPS_PROXY="http://<username>:<password>@<fqdn-proxy>:<proxy-port>"`
2. start Visual Studio Code via command `code`
3. configure Prisma Cloud plugin and connection test it's OK
4. start full scan

You can see the log of the "Run full Scan"

```text
2024-10-11 09:55:35 [info]: Initiating Prisma Cloud VS Code extension version 1.0.21 
2024-10-11 09:55:35 [info]: Plugin path: /Users/amusarra/.vscode/extensions/prismacloud.prisma-cloud-1.0.21 
2024-10-11 09:55:35 [info]: customer is not supporting SAST 
2024-10-11 09:55:35 [error]: Failed fetching a new JWT token, authorization on prisma failed: Request failed with status code 500 
2024-10-11 09:55:35 [error]: CustomersModulesService is not enabled Or token not exists {"isEnabled":true}
2024-10-11 09:55:35 [info]: customer is not supporting SAST 
2024-10-11 09:55:35 [info]: Installing Checkov with Docker 
2024-10-11 09:55:35 [error]: The Checkov installation with Docker was failed {"error":{"name":"Error","message":"Command failed: docker pull bridgecrew/checkov:latest\nCannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?\n","stack":"Error: Command failed: docker pull bridgecrew/checkov:latest\nCannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?\n\n    at genericNodeError (node:internal/errors:984:15)\n    at wrappedFn (node:internal/errors:538:14)\n    at ChildProcess.exithandler (node:child_process:423:12)\n    at ChildProcess.emit (node:events:519:28)\n    at ChildProcess.emit (node:domain:488:12)\n    at maybeClose (node:internal/child_process:1105:16)\n    at Socket.<anonymous> (node:internal/child_process:457:11)\n    at Socket.emit (node:events:519:28)\n    at Socket.emit (node:domain:488:12)\n    at Pipe.<anonymous> (node:net:339:12)"}}
2024-10-11 09:55:35 [info]: Installing Checkov with Pip3 
2024-10-11 09:55:35 [info]: Checking the Python version 
2024-10-11 09:55:37 [error]: No executor found for undefined, aborting scan operation 
2024-10-11 09:55:37 [info]: There are no installationId or jwtToken for sending analytics data 
2024-10-11 09:55:49 [info]: Successfully installed Checkov using pip3 {"type":"pip3","entrypoint":"checkov"}
2024-10-11 09:55:54 [info]: proxy settings: "" 
2024-10-11 09:55:54 [warn]: There are files opened from outside the workspace that won't be scanned in these directories: "/Users/amusarra/Library/Application Support/Code/logs/20241011T095522/window1/exthost/PrismaCloud.prisma-cloud" 
2024-10-11 09:55:54 [info]: checkov --repo-id vscode/extension --quiet --soft-fail --output json --bc-api-key  --directory "/Users/amusarra/dev/github/amusarra/tls-mutual-auth" 
2024-10-11 09:56:20 [info]: Full error checkov process output: 
2024-10-11 09:56:20,092 [MainThread  ] [WARNI]  An unexpected error occurred getting the run configuration from https://api.eu.prismacloud.io/bridgecrew/api/v2/checkov/runConfiguration after multiple retries. Please verify your API key and Prisma API URL, and retry. If the problem persists, please enable debug logs and contact support. The error is: HTTPSConnectionPool(host='api.eu.prismacloud.io', port=443): Max retries exceeded with url: /login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1493f79e0>, 'Connection to api.eu.prismacloud.io timed out. (connect timeout=3.1)'))
Traceback (most recent call last):
  File "/Users/amusarra/Library/Python/3.12/lib/python/site-packages/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amusarra/Library/Python/3.12/lib/python/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/Users/amusarra/Library/Python/3.12/lib/python/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/amusarra/Library/Python/3.12/lib/python/site-packages/urllib3/connectionpool.py", line 791, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/amusarra/Library/Python/3.12/lib/python/site-packages/urllib3/connectionpool.py", line 492, in _make_request
    raise new_e
  File "/Users/amusarra/Library/Python/3.12/lib/python/site-packages/urllib3/connectionpool.py", line 468, in _make_request
    self._validate_conn(conn)
  File "/Users/amusarra/Library/Python/3.12/lib/python/site-packages/urllib3/connectionpool.py", line 1097, in _validate_conn
    conn.connect()
  File "/Users/amusarra/Library/Python/3.12/lib/python/site-packages/urllib3/connection.py", line 611, in connect
    self.sock = sock = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/Users/amusarra/Library/Python/3.12/lib/python/site-packages/urllib3/connection.py", line 212, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x1493f79e0>, 'Connection to api.eu.prismacloud.io timed out. (connect timeout=3.1)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/amusarra/Library/Python/3.12/lib/python/site-packages/checkov/common/bridgecrew/platform_integration.py", line 1021, in get_customer_run_config
    token = self.get_auth_token()
            ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amusarra/Library/Python/3.12/lib/python/site-packages/cachetools/__init__.py", line 752, in wrapper
    v = func(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amusarra/Library/Python/3.12/lib/python/site-packages/checkov/common/bridgecrew/platform_integration.py", line 300, in get_auth_token
    request = self.http.request("POST", f"{self.prisma_api_url}/login",  # type:ignore[no-untyped-call]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amusarra/Library/Python/3.12/lib/python/site-packages/urllib3/_request_methods.py", line 118, in request
    return self.request_encode_body(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amusarra/Library/Python/3.12/lib/python/site-packages/urllib3/_request_methods.py", line 217, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amusarra/Library/Python/3.12/lib/python/site-packages/urllib3/poolmanager.py", line 443, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amusarra/Library/Python/3.12/lib/python/site-packages/urllib3/connectionpool.py", line 875, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/Users/amusarra/Library/Python/3.12/lib/python/site-packages/urllib3/connectionpool.py", line 875, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/Users/amusarra/Library/Python/3.12/lib/python/site-packages/urllib3/connectionpool.py", line 875, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/Users/amusarra/Library/Python/3.12/lib/python/site-packages/urllib3/connectionpool.py", line 845, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/Users/amusarra/Library/Python/3.12/lib/python/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.eu.prismacloud.io', port=443): Max retries exceeded with url: /login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1493f79e0>, 'Connection to api.eu.prismacloud.io timed out. (connect timeout=3.1)'))
An error occurred getting data from the platform, including policy metadata. Because --include-all-checkov-policies was not used, Checkov cannot differentiate Checkov-only policies from platform policies, and no policies will get evaluated. Please resolve the error above or re-run with the --include-all-checkov-policies argument (but note that this will not include any custom platform configurations or policy metadata).
 
2024-10-11 09:56:20 [info]: Checkov execution failed due to: The Checkov execution exited with code 2 

```

**Comment by ChananM** [comment]
@amusarra  Thank you for your examples!
Can you please try to achieve this in VS Code via the IDE settings?
Unfortunately I can't attach a screenshot due to corporate firewall. Just enter the settings page and search for 'proxy'
Either way, I reached out to my product manager to prioritize this issue

**Comment by amusarra** [comment]
Hi @ChananM 
I set the proxy directly on VSCode and that way it works, unlike when it is set via system environment.

![image](https://github.com/user-attachments/assets/07e314d8-a02a-4324-a679-4d5af8b7cdc7)

<img width="1656" alt="image" src="https://github.com/user-attachments/assets/29192fad-8767-44bd-b1d8-ed663f0c16b9">

**Comment by ChananM** [comment]
Thanks @amusarra 
Can you please reach out to your support representative so they will push for this fix?
Please tell them to refer to this issue in GitHub when opening a ticket

**Comment by amusarra** [comment]
Hi @ChananM many thanks. I will proceed as you advised.

**Comment by ChananM** [comment]
Hi @amusarra, can you confirm whether your proxy is only HTTP or can it be accessed with HTTPS as well?

**Comment by amusarra** [comment]
> Hi @amusarra, can you confirm whether your proxy is only HTTP or can it be accessed with HTTPS as well?

Hi. Only HTTP, no HTTPS.

**Comment by ChananM** [comment]
Hi @amusarra, please update the plugin to version `1.0.23` (or `1.0.23-203.241`, depending on your IDE version). It should contain the proxy support you need. Please update me if you have any issues with it.

**Comment by amusarra** [comment]
> Hi @amusarra, please update the plugin to version `1.0.23` (or `1.0.23-203.241`, depending on your IDE version). It should contain the proxy support you need. Please update me if you have any issues with it.

Hi @ChananM 
I have updated the plugin to version 1.0.23 and now obtains the below errors.

<img width="507" alt="image" src="https://github.com/user-attachments/assets/d942664d-c76e-4fde-9791-44733a4c5b6b">

```
cat /var/folders/cn/bdz5khhx1_7gn5ns89sbywtm0000gn/T/checkov1641997589836269429/error-dockerfile--debug-output8894913115974280725.txt
Traceback (most recent call last):
  File "/Users/amusarra/Library/Python/3.13/bin/checkov", line 2, in <module>
    from checkov.main import Checkov
  File "/Users/amusarra/Library/Python/3.13/lib/python/site-packages/checkov/main.py", line 22, in <module>
    from checkov.ansible.runner import Runner as ansible_runner
  File "/Users/amusarra/Library/Python/3.13/lib/python/site-packages/checkov/ansible/runner.py", line 5, in <module>
    from checkov.common.graph.checks_infra.registry import BaseRegistry
  File "/Users/amusarra/Library/Python/3.13/lib/python/site-packages/checkov/common/graph/checks_infra/registry.py", line 6, in <module>
    from checkov.common.graph.checks_infra import debug
  File "/Users/amusarra/Library/Python/3.13/lib/python/site-packages/checkov/common/graph/checks_infra/debug.py", line 13, in <module>
    from checkov.common.util.env_vars_config import env_vars_config
  File "/Users/amusarra/Library/Python/3.13/lib/python/site-packages/checkov/common/util/env_vars_config.py", line 7, in <module>
    from checkov.common.util.http_utils import normalize_bc_url
  File "/Users/amusarra/Library/Python/3.13/lib/python/site-packages/checkov/common/util/http_utils.py", line 6, in <module>
    import requests
  File "/Users/amusarra/Library/Python/3.13/lib/python/site-packages/requests/__init__.py", line 151, in <module>
    from . import packages, utils
  File "/Users/amusarra/Library/Python/3.13/lib/python/site-packages/requests/utils.py", line 24, in <module>
    from . import certs
  File "/Users/amusarra/Library/Python/3.13/lib/python/site-packages/requests/certs.py", line 14, in <module>
    from certifi import where
ImportError: cannot import name 'where' from 'certifi' (unknown location)

```

Thanks.

**Comment by amusarra** [comment]
Hi @ChananM 
After downgrade Python version to 3.11.10 obtains these errors.

```
❯ cat /var/folders/cn/bdz5khhx1_7gn5ns89sbywtm0000gn/T/checkov138113811154139288/error-bicep--debug-output1924460673092114364.txt
2024-10-29 11:52:40,870 [MainThread  ] [ERROR]  Exception traceback:
Traceback (most recent call last):
  File "/Users/amusarra/.local/lib/python3.11/site-packages/checkov/main.py", line 522, in run
    self.scan_reports = runner_registry.run(
                        ^^^^^^^^^^^^^^^^^^^^
  File "/Users/amusarra/.local/lib/python3.11/site-packages/checkov/common/runners/runner_registry.py", line 126, in run
    self.runners[0].run(root_folder, external_checks_dir=external_checks_dir, files=files,
  File "/Users/amusarra/.local/lib/python3.11/site-packages/checkov/bicep/runner.py", line 94, in run
    file_paths = get_scannable_file_paths(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amusarra/.local/lib/python3.11/site-packages/checkov/bicep/utils.py", line 35, in get_scannable_file_paths
    compiled = [re.compile(p.replace(".terraform", r"\.terraform")) for p in excluded_paths]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amusarra/.local/lib/python3.11/site-packages/checkov/bicep/utils.py", line 35, in <listcomp>
    compiled = [re.compile(p.replace(".terraform", r"\.terraform")) for p in excluded_paths]
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amusarra/.pyenv/versions/3.11.10/lib/python3.11/re/__init__.py", line 227, in compile
    return _compile(pattern, flags)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amusarra/.pyenv/versions/3.11.10/lib/python3.11/re/__init__.py", line 294, in _compile
    p = _compiler.compile(pattern, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amusarra/.pyenv/versions/3.11.10/lib/python3.11/re/_compiler.py", line 745, in compile
    p = _parser.parse(p, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amusarra/.pyenv/versions/3.11.10/lib/python3.11/re/_parser.py", line 989, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amusarra/.pyenv/versions/3.11.10/lib/python3.11/re/_parser.py", line 464, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amusarra/.pyenv/versions/3.11.10/lib/python3.11/re/_parser.py", line 691, in _parse
    raise source.error("nothing to repeat",
re.error: nothing to repeat at position 0
```

**Comment by amusarra** [comment]
Hi @ChananM 
I also notice this error on the system console.

```
2024-10-29 12:32:31 [ERROR] com.bridgecrew.api.PrismaApiClient - Call to '/bridgecrew/api/v1/plugins-analytics' ended with an error: 502 Bad Gateway: "{"message": "Internal server error"}"
org.springframework.web.client.HttpServerErrorException$BadGateway: 502 Bad Gateway: "{"message": "Internal server error"}"
	at org.springframework.web.client.HttpServerErrorException.create(HttpServerErrorException.java:108)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:186)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:137)
	at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:942)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:891)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:790)
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:672)
	at com.bridgecrew.api.PrismaApiClient.putDataAnalytics(PrismaApiClient.kt:113)
	at com.bridgecrew.analytics.AnalyticsService.releaseAnalytics(AnalyticsService.kt:168)
	at com.bridgecrew.analytics.AnalyticsService.startSchedulerReleasingAnalytics$lambda$2(AnalyticsService.kt:180)
	at com.bridgecrew.scheduler.IntervalRunner$scheduleWithTimer$1.run(IntervalRunner.kt:18)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
	at java.base/java.util.TimerThread.run(Timer.java:516)
2024-10-29 12:32:31 [INFO] c.b.scheduler.IntervalRunner - Interval function for Analytics executed with delay 2437
```

**Comment by ChananM** [comment]
@amusarra It's a known issue with bicep in Checkov. if you run `checkov -d <path> --skip-path "*" --framework bicep` in your terminal you will encounter the same problem. Something to do with the -skip-path when using a wildcard. If you need bicep scans in your work, I suggest opening a new ticket with support, this time regarding Checkov, and give them the command above. Otherwise, it shouldn't make much of a difference, and will be fixed eventually as part of a different initiative currently underway.

**Comment by ChananM** [comment]
@amusarra Regarding your 502 error, I can see in our logs we get timeout errors from our DB. I raised this issue internally, but I think the server is responding again
